sudo: required

language: python

python:
  - "2.7"

services:
  - docker

install: true

script:
  - docker build -t fest/rpi-packing-demo .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push fest/rpi-packing-demo;
    fi