kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: packing-demo
  name: packing-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: packing-demo
  template:
    metadata:
      labels:
        app: packing-demo
    spec:
      nodeSelector:
        target: master
      containers:
        - name: packing-demo
          securityContext:
            privileged: true
          image: fest/rpi-packing-demo
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /sys/class/gpio
              name:      sys-class-gpio
            - mountPath: /sys/devices
              name:      sys-devices
            - mountPath: /sys/bus
              name:      sys-bus
      volumes:
        - name:     sys-class-gpio
          hostPath:
            path:   /sys/class/gpio
        - name:     sys-devices
          hostPath:
            path:   /sys/devices
        - name:     sys-bus
          hostPath:
            path:   /sys/bus