# Default config file, that will be used if 'kubeconfig' parameter won't be specified by the user.
# Works with local clusters only.
apiVersion: v1
clusters:
- cluster:
    server: http://104.155.11.172:8080
  name: remote-server
contexts:
- context:
    cluster: remote-server
    user: myself
  name: default-context
current-context: default-context
kind: Config
preferences: {}
users:
- name: myself
  user:
    password: secret
    username: admin